### ISSUE TITLE
Ruby bundle install still on old 4.0.0 version

### ISSUE THREAD

**Issue by ghost** [astounding/mtik#13]
I'm using the new 4.0.4 release and it is great. However found I had to manually install it, where I couldn't refer to the new version via Gemfile and bundle install. Bundle install just goes and installs 4.0.0 version by default.
The mikrotik wiki, the readme, version docs on github and your website also refer to older version/s.

**Comment by juanfrancisco-18** [comment]
hola tengo la gema  instalada pero ejecuto este codigo :
<nowiki>
#!/usr/bin/env ruby 

require 'rubygems'
require 'mtik'

# Be verbose in output
MTik::verbose = true

# Connect to the device:
connection = MTik::Connection.new :host => '10.0.0.1', :user => 'admin', :pass => 'password'

# We are going to send a "monitor-traffic" command that will keep sending
# output until we "cancel" the command.  We only want to receive 10 responses:
$reply_limit = 10

# Execute the command:
$reply_count = 0
connection.get_reply_each(
  "/interface/monitor-traffic",
  "=interface=ether1",
  "=.proplist=rx-bits-per-second,tx-bits-per-second"
) do |request_object, reply_sentence|
  if reply_sentence.key?('!re')  # We only pay attention to reply sentences
    # Print the reply sentence:
    p reply_sentence

    # Increment the reply counter:
    $reply_count += 1

    # If we've reached our reply goal, cancel:
    if $reply_count >= $reply_limit
      # Cancel this command request:
      request_object.cancel
    end
  end
end

connection.close
</noqiki>

me dice que usuario y contraseña error. 

sera que alguien me puede ayudar?

**Comment by juanfrancisco-18** [comment]
> Estoy usando la nueva versión 4.0.4 y es genial. Sin embargo, descubrí que tenía que instalarlo manualmente, donde no podía referirme a la nueva versión a través de Gemfile y la instalación de paquetes. La instalación del paquete simplemente funciona e instala la versión 4.0.0 de forma predeterminada.
> El wiki de mikrotik, el archivo Léame, los documentos de versión en github y su sitio web también se refieren a versiones anteriores.

pero como descargo la nueva version? ya que mikrotik tiene la version 6.45.5

**Comment by alistairpullen** [comment]
I opened this thread originally, hoping Aaron D. Gifford the owner of the mtik gem would publish version 4.0.4 to https://rubygems.org/gems/mtik so that users of the gem can just Gemfile bundle install it from rubygems.org as a source. My reason for requesting it is because platforms like heroku dont let you bake in gem files manually.

**Comment by alistairpullen** [comment]
> 
> 
> > Estoy usando la nueva versión 4.0.4 y es genial. Sin embargo, descubrí que tenía que instalarlo manualmente, donde no podía referirme a la nueva versión a través de Gemfile y la instalación de paquetes. La instalación del paquete simplemente funciona e instala la versión 4.0.0 de forma predeterminada.
> > El wiki de mikrotik, el archivo Léame, los documentos de versión en github y su sitio web también se refieren a versiones anteriores.
> 
> pero como descargo la nueva version? ya que mikrotik tiene la version 6.45.5

mtik v4.0.4 is the Ruby gem version, not the Mikrotik OS version; both are unrelated to each other.

**Comment by alistairpullen** [comment]
I'm able to bundle install with the following in Gemfile instead:

gem 'mtik', '4.0.4', git: 'https://github.com/astounding/mtik'

We can close this issue, albeit the version on rubygems.org / your website / Microtik forums still refers to older version/s.

**Comment by astounding** [comment]
Sorry for taking so long--gems have been updated and pushed to rubygems.org.
