### ISSUE TITLE
new api login 

### ISSUE THREAD

**Issue by dorijan** [astounding/mtik#7]
Hi,
it seems Mikrotik has implemented new login api, so the old one is not working anymore.
Any change you can implement it?
https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

Thank you

**Comment by philomory** [comment]
Oddly enough, at least as of 6.43rc56, the old login API and the new login API both work. I'm not sure if that was intentional on Mikrotik's part, I've requested clarification on their forums.

**Comment by astounding** [comment]
Merged. Thanks for the new login stuff.

**Comment by xcdr** [comment]
Hi, when do You plan release updated gem version?

**Comment by juanfrancisco-18** [comment]
hola puedo conectarme a la api sin menester de la gema?

**Comment by juanfrancisco-18** [comment]
no veo que aqui nadie me responden

**Comment by alistairpullen** [comment]
As of routerboard release 6.45.6 the old login API pre-6.43 no longer works.
https://mikrotik.com/download/changelogs#show-tab-tree_2-id-f666cf9766423e0b33d43e79cf855217

I attempted to use the SSL API on my Heroku deployment and SSL handshake fails always, funny enough working fine when testing locally. Guess it is time to dig a bit deeper into that and fail over to using unencrypted_plaintext: true to allow usage of post-6.43 login method, at least until I get the SSL API working properly :)

**Comment by astounding** [comment]
Sorry for taking so long to release an "official" version of the gem to include the changes that have been present in the github repository for quite some time.  Method calls that pass the :ssl => true or the :unencrypted_plaintext => true arguments should use the newer-style (post RouterOS 6.43) API login method.

As of version 4.1.0, the scripts in bin/ also now support this via the --ssl | -s and --unencrypted_plaintext | -u CLI options OR via setting MTIK_SSL and/or MTIK_UNENCRYPTED_PLAINTEXT environment variables to accomplish something similar.

**Comment by juanfrancisco-18** [comment]
I am trying to login above 6.48.6 version but error sowing invalid username & password
